[package]
name = "meshtastic"
description = "A Rust library for communicating with and configuring Meshtastic devices."
homepage = "https://meshtastic.org/"
repository = "https://github.com/meshtastic/rust"
keywords = ["meshtastic", "mesh", "lora", "tcp", "serial"]
authors = ["Adam McQuilkin"]
readme = "README.md"
license = "GPL-3.0"
license-file = "LICENSE"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]

serde = ["dep:serde", "dep:serde_json"]
ts-gen = ["serde", "dep:specta"]

[[example]]
name = "basic_serial"

[[example]]
name = "basic_tcp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
prost-build = "0.11.1"
protoc-bin-vendored = "3.0.0"
walkdir = "2.3.2"

[dependencies]
futures-util = "0.3.28"
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["full"] }
tokio-serial = "5.4.4"
tokio-util = "0.7.8"
prost = "0.11.0"
log = "0.4.20"

specta = { git = "https://github.com/ajmcquilkin/specta.git", branch = "ajmcquilkin/ts-namespaces", ref = "2ba5af7", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
